### ISSUE TITLE
add the possibility to set the embedded chat to open on the cutomizable rocket chat home section?

### ISSUE THREAD

**Issue by wokawoka** [communiteq/discourse-rocketchat#1]
Would it be possible to add the possibility to set the embedded chat to open on the rocketchat home page and not on a default channel?

At the moment the only option is to set a default channel but having the embedded chat to open as well on the rocketchat customizable home page would also be very useful.

Thank you very much for the useful plugin!

**Comment by communiteq** [comment]
I have added this feature.
