### ISSUE TITLE
send icon misplaced

### ISSUE THREAD

**Issue by wokawoka** [communiteq/discourse-rocketchat#2]
Hello there!
I updated rocket chat to the last version and now the send icon in the embedded chat is misplaced (see attached picture)
It was in the right place before upgrading. 
Would you by change suggest a way to fix that? Maybe some css? 
Thank you!

![image](https://user-images.githubusercontent.com/7824587/137625460-ef0fccc3-8970-471e-9514-1b5e9b8122d0.png)

**Comment by communiteq** [comment]
Per https://meta.discourse.org/t/rocket-chat-sso-embed-plugin-for-discourse/199450/42 this is a Rocket.Chat issue.
